config/routes.rb
Rails.application.routes.draw do

	root "homes#home"
    get "/homes/thanks", to: "homes#thanks"
    get "/homes/about", to: "homes#about"

    devise_for :customers

	resource :customers, only:[:show] do
		member do
			get :edit_update
			patch :customers_update
			get :hide
			patch :hide_update
		end
	end
	resources :products, only:[:index, :show] do
		get :genre_product_index, on: :member
	end
	resources :destinations, only:[:index, :edit, :create, :update, :destroy]
	resources :orders, only:[:index, :show, :new, :create] do
   	collection do
			post :confirm, to: "orders/confirm"
		end
	end
	resources :carts, only:[:index, :create, :update, :destroy] do
		delete :destroy_all, on: :member
	end

	devise_for :staffs

	namespace :staffs do
		root "homes#top"
		get 'searchs/search', to:'searches#search'
		get 'orders/today', to:'orders#index_today'

		resources :customers, only:[:index, :show, :edit, :update]do
			member do
				get :customer_orders
			end
		end
		resources :products, only:[:index, :show, :new, :edit, :create, :update]
		resources :genres, only:[:index, :edit, :create, :update]
		resources :orders, only:[:index, :show]do
			member do
				patch :update_for_orderstatus
				patch :update_for_orderstatus_individual
				get :show_individual
			end
		end
		resources :details, only:[]do
			member do
				patch :update_for_productionstatus
				patch :update_for_productionstatus_individual
			end
		end
	end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :carts

  belongs_to :genre

  attachment :image

  validates :name, presence: true
  validates :price, presence: true
  validates :explain, presence: true
  validates :sale_status, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
    @products = Product.all
    @genres = Genre.all
	end

  def show
    @product = Product.find(params[:id])
    @cart = Cart.new
    @genres = Genre.all
  end

  def genre_product_index
    @genres = Genre.all
    @genre = Genre.find(params[:id])
    @products = @genre.products.all
  end
end

app/controllers/staffs/confirmations_controller.rb
# frozen_string_literal: true

class Staffs::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/staffs/customers_controller.rb
class Staffs::CustomersController < ApplicationController
	before_action :authenticate_staff!
	def index
        @customers = Customer.all
	end

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
		@customer.update(customer_params)
		redirect_to staffs_customer_path(@customer)
	end

	def customer_orders
		@customer = Customer.find(params[:id])
	end

	private
	def customer_params
		params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :tel, :email, :postal_code, :address, :customer_status)
	end

end

app/controllers/staffs/details_controller.rb
class Staffs::DetailsController < ApplicationController
	before_action :authenticate_staff!
	def update_for_productionstatus
		@detail = Detail.find(params[:id])
		@detail.update(detail_params)

		@order = Order.where(id: @detail.order_id)
		@details = Detail.where(order_id: @detail.order_id)

		if @details.pluck(:production_status).include?("製作中")
			@order.update(order_status: "製作中")

		elsif @details.pluck(:production_status).uniq == ["制作完了"]
			@order.update(order_status: "発送準備中")

		end

		redirect_to staffs_orders_path
	end

	def update_for_productionstatus_individual
		@detail = Detail.find(params[:id])
		@detail.update(detail_params)

		@order = Order.where(id: @detail.order_id)
		@details = Detail.where(order_id: @detail.order_id)

		if @details.pluck(:production_status).include?("製作中")
			@order.update(order_status: "製作中")

		elsif @details.pluck(:production_status).uniq == ["制作完了"]
			@order.update(order_status: "発送準備中")

		end

		redirect_to customer_orders_staffs_customer_path(@detail.order.customer_id)
	end

	private
	def detail_params
	params.require(:detail).permit(:production_status)
	end
end

app/controllers/staffs/genres_controller.rb
class Staffs::GenresController < ApplicationController
	before_action :authenticate_staff!
	def create
		@genre = Genre.new(genre_params)
		if @genre.save
			redirect_to staffs_genres_path
		else
			@genres = Genre.all
			render :index
		end
	end

	def index
		@genre = Genre.new
		@genres = Genre.all
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
		if @genre.update(genre_params)
			redirect_to staffs_genres_path
		else
			render :edit
		end
	end

	private
	def genre_params
        params.require(:genre).permit(:category_name, :genre_status)
    end
end

app/controllers/staffs/homes_controller.rb
class Staffs::HomesController < ApplicationController
  before_action :authenticate_staff!
	def top
		@orders = Order.all
	end
end

app/controllers/staffs/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Staffs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/staffs/orders_controller.rb
class Staffs::OrdersController < ApplicationController
	before_action :authenticate_staff!
	def index
		@orders = Order.all
	end

	def show
		@order = Order.find(params[:id])
	end

	def show_individual
		@order = Order.find(params[:id])
	end

	def update_for_orderstatus
		@order = Order.find(params[:id])
		@order.update(order_params)
		if @order.order_status == "入金確認"
			@details = Detail.where(order_id: @order.id)
			@details.each do |detail|
				detail.update(production_status: "制作待ち")
			end
		end

		@orders = Order.all
		render :index
	end

	def update_for_orderstatus_individual
		@order = Order.find(params[:id])
		@order.update(order_params)
		if @order.order_status == "入金確認"
			@details = Detail.where(order_id: @order.id)
			@details.each do |detail|
				detail.update(production_status: "制作待ち")
			end
		end

		@orders = Order.all
		redirect_to customer_orders_staffs_customer_path(@order.customer_id)
	end

	def index_today
		@orders = Order.all
	end

	private
	def order_params
	params.require(:order).permit(:order_status)
	end
end

app/controllers/staffs/passwords_controller.rb
# frozen_string_literal: true

class Staffs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/staffs/products_controller.rb
class Staffs::ProductsController < ApplicationController
	before_action :authenticate_staff!
	def new
		@product = Product.new
		@genres = Genre.where(genre_status: true)

	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to staffs_product_path(@product)
		else
			@genres = Genre.where(genre_status: true)
			render :new
		end
	end

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		@genre = @product.genre
		@category_name = @genre.category_name
	end

	def edit
		@product = Product.find(params[:id])
		@genres = Genre.where(genre_status: true)
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to staffs_product_path(@product)
		else
			@genres = Genre.where(genre_status: true)
			render :edit
		end
	end

	private
	def product_params
		params.require(:product).permit(:image, :name, :explain, :genre_id, :price, :sale_status, :recommend_status)
	end
end

app/controllers/staffs/registrations_controller.rb
# frozen_string_literal: true

class Staffs::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/staffs/searches_controller.rb
class Staffs::SearchesController < ApplicationController
	before_action :authenticate_staff!
	def search
		@customers = Customer.search(params[:search])
		@products = Product.search(params[:search])
	end

    def Customer.search(search)
	    if search
	      Customer.where(['last_name LIKE ? OR first_name LIKE ? OR email LIKE ?',"%#{search}%","%#{search}%","%#{search}%"])
	    else
	      Customer.all
	    end
  	end

	def Product.search(search)
		if search
		Product.where(['name LIKE ? OR explain LIKE ?',"%#{search}%","%#{search}%"])
		else
		Product.all
		end
	end

end

app/controllers/staffs/sessions_controller.rb
# frozen_string_literal: true

class Staffs::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/staffs/unlocks_controller.rb
# frozen_string_literal: true

class Staffs::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staffs/customers_helper.rb
module Staffs::CustomersHelper
end

app/helpers/staffs/details_helper.rb
module Staffs::DetailsHelper
end

app/helpers/staffs/genres_helper.rb
module Staffs::GenresHelper
end

app/views/staffs/products/edit.html.erb
<div class="container staffs_product_edit">

	<%= render 'layouts/errors', model: @product %>

	<div class="row">
		<div class="col-xs-5 col-xs-offset-1">
			<span style="display: block; margin-bottom: 30px; background-color: #cccccc; text-align: center;">
				<h3>商品編集</h3>
			</span>
		</div>
	</div>
</div>


		<%= form_for(@product,url:staffs_product_path) do |f| %>
			<form class="form-horizontal" role="form">

				<div class="container">
					<div class="row">
						<div class="col-xs-4  col-xs-offset-1">
							<%= attachment_image_tag(@product, :image, fallback: "no_image.jpg", class: "product_image_edit")  %>
							<%= f.attachment_field :image %>
						</div>




						<div class="col-xs-4">
							<div class="container">

								<div class="row" style="margin-bottom: 20px;">
									<div class="col-xs-2">
										<%= f.label :name, '商品名', class: 'control-label' %>
									</div>
									<div class="col-xs-2">
										<%= f.text_field :name %>
									</div>
								</div>

								<div class="row" style="margin-bottom: 20px;">
									<div class="col-xs-2">
										<%= f.label :explain, '商品説明', class: 'control-label' %>
									</div>
									<div class="col-xs-2">
										<%= f.text_area :explain %>
									</div>
								</div>

								<div class="row" style="margin-bottom: 20px;">
									<div class="col-xs-2">
										<%= f.label :genre_id, 'ジャンル', class: 'control-label' %>
									</div>
									<div class="col-xs-2">
										<%= f.collection_select :genre_id, @genres, :id, :category_name, include_blank: "選択して下さい" %>
									</div>
								</div>

								<div class="row" style="margin-bottom: 20px;">
									<div class="col-xs-2">
										<%= f.label :price, '税抜き価格', class: 'control-label' %>
									</div>
									<div class="col-xs-2">
										<%= f.text_field :price %>
									</div>
								</div>

								<div class="row" style="margin-bottom: 20px;">
									<div class="col-xs-2">
										<%= f.label :sale_status, '販売ステータス', class: 'control-label' %>
									</div>
									<div class="col-xs-2">
										<%= f.select :sale_status,[["販売中", "1"], ["売切れ", "2"]], include_blank: "選択して下さい" %>
									</div>
								</div>

								<div class="row" style="margin-bottom: 20px;">
									<div class="col-xs-2">
										<%= f.label :recommend_status, 'おすすめステータス', class: 'control-label' %>
									</div>
									<div class="col-xs-2">
										<%= f.select :recommend_status,[["おすすめ", "1"], ["普通", "2"]], include_blank: "選択して下さい" %>
									</div>
								</div>

								<div class="row">
									<div class="col-xs-6">
		        					<%= f.submit '変更を保存', class: "btn btn-primary pull-right"%>
		        					</div>
		        				</div>
	        				</div>
	        			</div>
	        		</div>
	        	</div>
        	</form>
  			<% end %>

app/views/staffs/products/index.html.erb
<div class="container staffs_product_index">
	<div class="row">
		<div class="col-xs-4 col-xs-offset-1">
			<span style="display: block; margin-bottom: 10px; background-color: #cccccc; text-align: center;">
				<h3>商品一覧</h3>
			</span>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">

            <p class="text-right">
	            <%= link_to new_staffs_product_path(@product), data: {"turbolinks" => false} do %>
					<button class="btn-circle-kirby" style="outline: 0;display: inline-block; text-decoration: none; color: #f9a9ae; width: 35px; height: 35px; line-height: 20px; border-radius: 50%; text-align: center; overflow: hidden; font-weight: bold; background-image: linear-gradient(#fed6e3 0%, #ffaaaa 100%); text-shadow: 1px 1px 1px rgba(255, 255, 255, 0.66); box-shadow: 0 1px 1px rgba(0, 0, 0, 0.28);">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					</button>
				<% end %>
		    </p>

			<table class="table ">
				<thead>
					<tr class="active">
						<th>商品ID</th>
						<th>商品名</th>
						<th>税抜価格</th>
						<th>ジャンル</th>
						<th>販売ステータス</th>
						<th>おすすめステータス</th>
					</tr>
				</thead>
				<tbody>
					<% @products.each do |product| %>
					<tr>
						<td><%= product.id %></td>
						<td>
							<u><%= link_to product.name, staffs_product_path(product.id), class: "product_#{product.id}" %></u>
						</td>
						<td><%= product.price %></td>
						<td><%= product.genre.category_name %></td>
						<td>
						    <% if product.sale_status == 1 %> 
							<p>販売中</p>
							<% else %>
							<p>売切れ</p>
							<% end %>
						</td>
						<td>
						    <% if product.recommend_status == 1 %> 
							<p>おすすめ</p>
							<% else %>
							<p>普通</p>
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/staffs/products/new.html.erb
<div class="container staffs_product_new">
	<%= render 'layouts/errors', model: @product %>

	<dix class="row">
		<div class="col-xs-5">

			<div class="row">
				<div class="col-xs-8 col-xs-offset-2">
					<span class="pull-left" style="background-color: #C0C0C0; font-size: 2.0em; margin-bottom: 40px;">
						商品新規登録
					</span>
				</div>
			</div>

          	<%= form_for(@product,url:staffs_products_path) do |f| %>
          	<form class="form-horizontal" role="form">

          		<div class="container">
          			<div class="row">

          				<div class="col-xs-4">
							<%= attachment_image_tag(@product, :image, size:'200x200', fallback: "no_image.jpg") %>
							<%= f.attachment_field :image, class: "product_image" %>
						</div>

						<div class="col-xs-8">

							<div class="row" style="margin-bottom: 20px;">
								<div class="col-xs-2">
									<%= f.label :name, '商品名', class: 'control-label' %>
								</div>
								<div class="col-xs-2">
									<%= f.text_field :name %>
								</div>
							</div>

							<div class="row" style="margin-bottom: 20px;">
								<div class="col-xs-2">
									<%= f.label :explain, '商品説明', class: 'control-label' %>
								</div>
								<div class="col-xs-2">
									<%= f.text_area :explain %>
								</div>
							</div>

							<div class="row" style="margin-bottom: 20px;">
								<div class="col-xs-2">
									<%= f.label :genre_id, 'ジャンル', class: 'control-label' %>
								</div>
								<div class="col-xs-2">
									<%= f.collection_select :genre_id, @genres, :id, :category_name, include_blank: "--選択して下さい--" %>
								</div>
							</div>

							<div class="row" style="margin-bottom: 20px;">
								<div class="col-xs-2">
									<%= f.label :price, '税抜き価格', class: 'control-label' %>
								</div>
								<div class="col-xs-2">
									<%= f.text_field :price %>
								</div>
							</div>

							<div class="row" style="margin-bottom: 20px;">
								<div class="col-xs-2">
									<%= f.label :sale_status, '販売ステータス', class: 'control-label' %>
								</div>
								<div class="col-xs-2">
									<%= f.select :sale_status,[["販売中", "1"], ["売切れ", "2"]], include_blank: "--選択して下さい--" %>
								</div>
							</div>

							<div class="row" style="margin-bottom: 20px;">
								<div class="col-xs-2">
									<%= f.label :recommend_status, 'おすすめステータス', class: 'control-label' %>
								</div>
								<div class="col-xs-2">
									<%= f.select :recommend_status,[["おすすめ商品", "1"], ["普通", "2"]], include_blank: "--選択して下さい--" %>
								</div>
							</div>

							<div class="row">
								<div class="col-xs-6">
	    							<%= f.submit '新規登録', class: "btn btn-primary pull-right"%>
	    						</div>
	    					</div>
	    				</div>
	    			</div>
	    		</div>
	    	</form>
	    	<% end %>
		

app/views/staffs/products/show.html.erb
<div class="container staffs_product_show">
	<div class="row">
		<div class="col-xs-4 col-xs-offset-1">
			<span style="display: block; margin-bottom: 30px; background-color: #cccccc; text-align: center;">
				<h3>商品詳細</h3>
			</span>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-xs-4">
			<div class="image" style="margin-left: 80px;">
				<%= attachment_image_tag(@product, :image, format: 'jpeg', class: "img-square pull-left product_image", fallback: "no_image.jpg") %>
			</div>
		</div>

		<div class="col-xs-6 col-xs-offset-2">
			<div class="table-responsive">
				<table class="table">
					<tbody>
						<tr>
							<th style="border: none;">商品名</th>
							<td style="border: none;"><%= @product.name %><td>
						</tr>
						<tr>
							<th style="border: none;">商品説明</th>
							<td style="border: none;"><%= @product.explain %></td>
						</tr>
						<tr>
							<th style="border: none;">ジャンル</th>
							<td style="border: none;"><%= @category_name %></td>
						</tr>
						<tr>
							<th style="border: none;">税込価格（税抜き価格)</th>
							<td style="border: none;">
								<% addtax= @product.price * 1.1 %>
								<%= addtax.round %>円(<%= @product.price %>円）
							</td>
						</tr>
						<tr>
							<th style="border: none;">販売ステータス</th>
							<td style="border: none;">
								<% if @product.sale_status == 1 %>
								<p>販売中</p>
								<% else %>
								<p>売切れ</p>
								<% end %>
							</td>
						</tr>
						<tr>
							<th style="border: none;">おすすめステータス</th>
							<td style="border: none;">
								<% if @product.recommend_status == 1 %>
								<p>おすすめ</p>
								<% else %>
								<p>普通</p>
								<% end %>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<%= link_to '編集する', edit_staffs_product_path(@product), class: "btn btn-primary pull-right", data: {"turbolinks" => false} %>

	</div>
</div>