config/routes.rb
Rails.application.routes.draw do

	root "homes#home"
    get "/homes/thanks", to: "homes#thanks"
    get "/homes/about", to: "homes#about"

    devise_for :customers

	resource :customers, only:[:show] do
		member do
			get :edit_update
			patch :customers_update
			get :hide
			patch :hide_update
		end
	end
	resources :products, only:[:index, :show] do
		get :genre_product_index, on: :member
	end
	resources :destinations, only:[:index, :edit, :create, :update, :destroy]
	resources :orders, only:[:index, :show, :new, :create] do
   	collection do
			post :confirm, to: "orders/confirm"
		end
	end
	resources :carts, only:[:index, :create, :update, :destroy] do
		delete :destroy_all, on: :member
	end

	devise_for :staffs

	namespace :staffs do
		root "homes#top"
		get 'searchs/search', to:'searches#search'
		get 'orders/today', to:'orders#index_today'

		resources :customers, only:[:index, :show, :edit, :update]do
			member do
				get :customer_orders
			end
		end
		resources :products, only:[:index, :show, :new, :edit, :create, :update]
		resources :genres, only:[:index, :edit, :create, :update]
		resources :orders, only:[:index, :show]do
			member do
				patch :update_for_orderstatus
				patch :update_for_orderstatus_individual
				get :show_individual
			end
		end
		resources :details, only:[]do
			member do
				patch :update_for_productionstatus
				patch :update_for_productionstatus_individual
			end
		end
	end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :destinations, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :tel, presence: true
  validates :address, presence: true

  def active_for_authentication?
    super && (self.customer_status == false)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	before_action :authenticate_customer!
	def show
		@customer = current_customer
	end

	def edit_update
		@customer =current_customer
	end

	def customers_update
		@customer = current_customer
		if @customer.update(customer_params)
			redirect_to customers_path
		else
			render :edit_update
		end
	end

	def hide
		
	end
	def hide_update
		@customer = current_customer
		@customer.update(customer_status: true)
		reset_session
		redirect_to root_path
	end

	private
	def customer_params
		params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :tel, :email, :postal_code, :address)
	end
	
end

app/controllers/staffs/customers_controller.rb
class Staffs::CustomersController < ApplicationController
	before_action :authenticate_staff!
	def index
        @customers = Customer.all
	end

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
		@customer.update(customer_params)
		redirect_to staffs_customer_path(@customer)
	end

	def customer_orders
		@customer = Customer.find(params[:id])
	end

	private
	def customer_params
		params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :tel, :email, :postal_code, :address, :customer_status)
	end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/staffs/customers_helper.rb
module Staffs::CustomersHelper
end

app/views/customers/edit_update.html.erb
<div class="container">

	<%= render 'layouts/errors', model: @customer %>

	<div class="row">
		<div class="col-xs-4 col-xs-offset-1">
			<span style="display: block; margin-bottom: 30px; background-color: #cccccc; text-align: center;">
				<h3>登録情報編集</h3>
			</span>
		</div>
	</div>
</div>

<%= form_for(@customer,url:customers_update_customers_path) do |f| %>
<div class="container">
	<div class="row">
		<div class="col-xs-12">

			<div class="form-group">
			    <div class="field row">
			    	<%= f.label :name, "名前", class: "col-xs-3" %>
			      		<div class="col-xs-1 text-right">(姓)</div>
			      	<%= f.text_field :last_name, class: "col-xs-2" %>
			      		<div class="col-xs-1 text-right">(名)</div>
			      	<%= f.text_field :first_name, class: "col-xs-2" %>
			    </div>
		  	</div>

			<div class="form-group">
			    <div class="field row">
			    	<%= f.label :name_kana, "フリガナ", class: "col-xs-3" %>
			      		<div class="col-xs-1 text-right">(セイ)</div>
			      	<%= f.text_field :last_name_kana, class: "col-xs-2" %>
			      		<div class="col-xs-1 text-right">(メイ)</div>
			      	<%= f.text_field :first_name_kana, class: "col-xs-2" %>
			    </div>
		  	</div>

		  	<div class="form-group">
			    <div class="field row">
			    	<%= f.label :email, "メールアドレス", class: "col-xs-3" %>
			    	<%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-xs-2 col-xs-offset-1" %>
			    </div>
			</div>

			<div class="form-group">
			    <div class="field row">
			    	<%= f.label :postal_code, "郵便番号(ハイフンなし)", class: "col-xs-3" %>
			    	<%= f.text_field :postal_code, class: "col-xs-2 col-xs-offset-1" %>
			    </div>
		  	</div>

		  	<div class="form-group">
			    <div class="field row">
			    	<%= f.label :address, "住所", class: "col-xs-3" %>
			    	<%= f.text_field :address, class: "col-xs-5 col-xs-offset-1" %>
			    </div>
			</div>

			<div class="form-group">
			    <div class="field row">
				    <%= f.label :tel, "電話番号(ハイフンなし)", class: "col-xs-3" %>
				    <%= f.text_field :tel, class: "col-xs-2 col-xs-offset-1" %>
			    </div>
			</div>

		    <div class="row", style="margin-top: 50px;">
		    	<div class="col-xs-6" style="display: flex; justify-content: space-between;">
	        		<%= f.submit '編集内容を保存する', class: "btn btn-primary"%>
		        	<div class="h" style="display: inline-block; margin-left: 40px;">
		        	<%= link_to '退会する', hide_customers_path, class: "btn btn-danger"%>
		        	</div>
	        	</div>
	    	</div>
	    </div>
	</div>
</div>
<% end %>

app/views/customers/hide.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">


			<h3 class="text-center">本当に退会しますか？</h3>

		</div>
	</div>
</div>
<br>
<br>

<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">


			<p class="text-center">退会すると、会員登録情報や<br>
			これまでの購入履歴が観覧できなくなります。<br>
			退会するには、「退会する」をクリックしてください。</p>

		</div>
	</div>
</div>

<br>


<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<p class="text-center">

		<%= link_to ' 退会しない', customers_path, class: "btn btn-primary" %>

		<%= link_to "退会する", hide_update_customers_path(current_customer), method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>

			</p>
		</div>
	</div>
</div>

app/views/customers/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-4 col-xs-offset-1">
			<span style="display: block; margin-bottom: 30px; background-color: #cccccc; text-align: center;">
				<h3>マイページ</h3>
			</span>
		</div>
	</div>
</div>
<div class="container">
	<div class="row" style="margin-left: 10px;">
		<div class="col-xs-8 col-xs-offset-1">
			<strong>登録情報</strong>
			<span class="link", style="margin-left: 20px;">
				<%= link_to '編集する', edit_update_customers_path(@customer), class: "btn btn-primary", data: {"turbolinks" => false} %>
			</span>
			<span class="link", style="margin-left: 20px;">
				<%= link_to 'パスワードを変更する', edit_customer_registration_path(@customer), class: "btn btn-primary", data: {"turbolinks" => false} %>
			</span>
		</div>
	</div>
	<div class="row" style="margin-top: 30px;">
		<div class="col-xs-8 col-xs-offset-1">
			<div class="table-responsive">
				<table class="table table-bordered">
					<tbody>
						<tr>
							<th class="active col-xs-2">氏名</th>
							<td class="col-xs-8">
								<%= @customer.last_name %><%= @customer.first_name %>
							</td>
						</tr>
						<tr>
							<th class="active col-xs-2">カナ</th>
							<td class="col-xs-8">
								<%= @customer.last_name_kana %>
								<%= @customer.first_name_kana %>
							</td>
						</tr>
						<tr>
							<th class="active col-xs-2">郵便番号</th>
							<td class="col-xs-8">
								<%= @customer.postal_code %>
							</td>
						</tr>
						<tr>
							<th class="active col-xs-2">住所</th>
							<td class="col-xs-8">
								<%= @customer.address %>
							</td>
						</tr>
						<tr>
							<th class="active col-xs-2">電話番号</th>
							<td class="col-xs-8">
								<%= @customer.tel %>
							</td>
						</tr>
						<tr>
							<th class="active col-xs-2">メールアドレス</th>
							<td class="col-xs-8">
								<%= @customer.email %>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>

	<div class="row" style="margin-top: 20px; margin-left: 10px;">
		<div class="col-xs-8 col-xs-offset-1">
			<strong>配送先</strong>
			<span class="link", style="margin-left: 45px;">
				<%= link_to '一覧を見る', destinations_path, class: "btn btn-primary", data: {"turbolinks" => false} %>
			</span>
		</div>
	</div>
	<div class="row" style="margin-top: 20px; margin-left: 10px;">
		<div class="col-xs-8 col-xs-offset-1">
			<strong>注文履歴</strong>
			<span class="link", style="margin-left: 30px;">
				<%= link_to '一覧を見る', orders_path, class: "btn btn-primary", data: {"turbolinks" => false} %>
			</span>
		</div>
	</div>
</div>