config/routes.rb
Rails.application.routes.draw do

	root "homes#home"
    get "/homes/thanks", to: "homes#thanks"
    get "/homes/about", to: "homes#about"

    devise_for :customers

	resource :customers, only:[:show] do
		member do
			get :edit_update
			patch :customers_update
			get :hide
			patch :hide_update
		end
	end
	resources :products, only:[:index, :show] do
		get :genre_product_index, on: :member
	end
	resources :destinations, only:[:index, :edit, :create, :update, :destroy]
	resources :orders, only:[:index, :show, :new, :create] do
   	collection do
			post :confirm, to: "orders/confirm"
		end
	end
	resources :carts, only:[:index, :create, :update, :destroy] do
		delete :destroy_all, on: :member
	end

	devise_for :staffs

	namespace :staffs do
		root "homes#top"
		get 'searchs/search', to:'searches#search'
		get 'orders/today', to:'orders#index_today'

		resources :customers, only:[:index, :show, :edit, :update]do
			member do
				get :customer_orders
			end
		end
		resources :products, only:[:index, :show, :new, :edit, :create, :update]
		resources :genres, only:[:index, :edit, :create, :update]
		resources :orders, only:[:index, :show]do
			member do
				patch :update_for_orderstatus
				patch :update_for_orderstatus_individual
				get :show_individual
			end
		end
		resources :details, only:[]do
			member do
				patch :update_for_productionstatus
				patch :update_for_productionstatus_individual
			end
		end
	end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :vol, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_customer!
	def index
    @carts = current_customer.carts.all
    array = []
    @carts.each do |carts|
      array << carts.product.price * carts.vol
    end
    subtotal = array.sum
    @total = (subtotal * 1.1).round
	end

  def create
    if current_customer.carts.exists?(product_id: params[:cart][:product_id])
      cart = Cart.find_by(product_id: params[:cart][:product_id])
      cart.increment(:vol, params[:cart][:vol].to_i)
      cart.save
      redirect_to carts_path
    else
      cart = Cart.new(cart_params)
      cart.customer_id = current_customer.id
      if cart.save
        redirect_to carts_path
      else
        @product = Product.find(params[:cart][:product_id])
        @cart = Cart.new
        @genres = Genre.all
        render "products/show"
      end
    end
  end

  def update
    @cart = current_customer.carts.find(params[:id])
    @cart.update(cart_params)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    cart = Cart.find(params[:id])
    cart.destroy
    redirect_to carts_path
  end

  def destroy_all
    current_customer.carts.destroy_all
    redirect_to carts_path
  end

  private
  def cart_params
    params.require(:cart).permit(:vol, :product_id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<div class="container">
  <div class="row">
    <span class="pull-left" style="background-color: #cccccc; font-size: 2.0em; margin-bottom: 10px;">ショッピングカート
    </span>

    <%= link_to 'カートを空にする', destroy_all_cart_path(current_customer), method: :delete, class: "btn btn-danger pull-right" %>

    <table class="table table-bordered">
      <thead>
        <tr class="active">
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @carts.each do |cart| %>
          <tr>
            <td><%= attachment_image_tag cart.product, :image, fallback: "no_image.jpg", width: "auto", height: "50" %>　<%= cart.product.name %></td>
            <td><% addtax = cart.product.price * 1.1 %>
                <%= addtax.round %></td>
            <td>
              <%= form_for(cart) do |f| %>
                <%= f.number_field :vol %>
                <%= f.submit "変更",class: "btn btn-primary" %>
              <% end %>
            </td>
            <td>￥　<% subtotal = addtax * cart.vol %>
              <%= subtotal.round %></td>
            <td>
              <%= link_to '削除する', cart_path(cart), method: :delete, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-xs-1">
      <%= link_to '買い物を続ける', root_path, class: "btn btn-primary" %>
    </div>
    <div class="col-xs-3 col-xs-offset-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="active">請求金額</th>
            <th><%= @total %></th>
          </tr>
        </thead>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2 col-xs-offset-5">
      <% if !(@carts.empty?) %>
        <%= link_to '情報入力に進む', new_order_path, data: {"turbolinks" => false}, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>