config/routes.rb
Rails.application.routes.draw do

	root "homes#home"
    get "/homes/thanks", to: "homes#thanks"
    get "/homes/about", to: "homes#about"

    devise_for :customers

	resource :customers, only:[:show] do
		member do
			get :edit_update
			patch :customers_update
			get :hide
			patch :hide_update
		end
	end
	resources :products, only:[:index, :show] do
		get :genre_product_index, on: :member
	end
	resources :destinations, only:[:index, :edit, :create, :update, :destroy]
	resources :orders, only:[:index, :show, :new, :create] do
   	collection do
			post :confirm, to: "orders/confirm"
		end
	end
	resources :carts, only:[:index, :create, :update, :destroy] do
		delete :destroy_all, on: :member
	end

	devise_for :staffs

	namespace :staffs do
		root "homes#top"
		get 'searchs/search', to:'searches#search'
		get 'orders/today', to:'orders#index_today'

		resources :customers, only:[:index, :show, :edit, :update]do
			member do
				get :customer_orders
			end
		end
		resources :products, only:[:index, :show, :new, :edit, :create, :update]
		resources :genres, only:[:index, :edit, :create, :update]
		resources :orders, only:[:index, :show]do
			member do
				patch :update_for_orderstatus
				patch :update_for_orderstatus_individual
				get :show_individual
			end
		end
		resources :details, only:[]do
			member do
				patch :update_for_productionstatus
				patch :update_for_productionstatus_individual
			end
		end
	end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :carts

  belongs_to :genre

  attachment :image

  validates :name, presence: true
  validates :price, presence: true
  validates :explain, presence: true
  validates :sale_status, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
    @products = Product.all
    @genres = Genre.all
	end

  def show
    @product = Product.find(params[:id])
    @cart = Cart.new
    @genres = Genre.all
  end

  def genre_product_index
    @genres = Genre.all
    @genre = Genre.find(params[:id])
    @products = @genre.products.all
  end
end

app/controllers/staffs/products_controller.rb
class Staffs::ProductsController < ApplicationController
	before_action :authenticate_staff!
	def new
		@product = Product.new
		@genres = Genre.where(genre_status: true)

	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to staffs_product_path(@product)
		else
			@genres = Genre.where(genre_status: true)
			render :new
		end
	end

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		@genre = @product.genre
		@category_name = @genre.category_name
	end

	def edit
		@product = Product.find(params[:id])
		@genres = Genre.where(genre_status: true)
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to staffs_product_path(@product)
		else
			@genres = Genre.where(genre_status: true)
			render :edit
		end
	end

	private
	def product_params
		params.require(:product).permit(:image, :name, :explain, :genre_id, :price, :sale_status, :recommend_status)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staffs/products_helper.rb
module Staffs::ProductsHelper
end

app/views/products/_list.html.erb
<h4>ジャンル検索</h4>
<table class="table">
  <tbody>
    <% genres.each do |genre| %>
	    <% if genre.genre_status == true %>
		    <tr>
		      <th>
		        <%= link_to genre.category_name, genre_product_index_product_path(genre) %>
		      </th>
		    </tr>
		<% end %>
    <% end %>
  </tbody>
</table>

app/views/products/genre_product_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'products/list', genres: @genres %>
    </div>

    <div class="col-xs-9">
      <div class="row">
        <span class="pull-left" style="font-size: 2.0em; margin-bottom: 10px;"><%= @genre.category_name %>一覧
        </span>
        <span>（全<%= @products.count %>件）</span>
      </div>
      <div class="row">

        <% @products.each do |product| %>
          <div class="col-xs-3">
          <div class="row">
            <%= link_to product_path(product.id) do %>
              <%= attachment_image_tag product, :image, fallback: "no_image.jpg", width: "auto", height: "100" %>
            <% end %>
          </div>
          <div class="row"><%= product.name %></div>
          <div class="row">￥<%= product.price %></div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'products/list', genres: @genres %>
    </div>

    <div class="col-xs-9">
      <h2>商品一覧</h2>
      <span>（全<%= @products.count %>件）</span>
      <div class="row">

        <% @products.each do |product| %>
          <div class="col-xs-3 mx-auto">
          <div class="row">
            <%= link_to product_path(product.id) do %>
              <%= attachment_image_tag product, :image, fallback: "no_image.jpg", width: "auto", height: "100", class: "text-center" %>
            <% end %>
          </div>
          <div class="row">
            <%= product.name %>
              <% if product.sale_status  == 1 %>
               (販売中)
              <% else %>
               (売り切れ)
              <% end %>
            </div>
          <div class="row">￥<%= product.price %></div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'products/list', genres: @genres %>
    </div>

    <div class="col-xs-8 col-xs-offset-1">
      <h2>商品詳細</h2>
      <div class="row">
        <div class="col-xs-7">
          <%= attachment_image_tag @product, :image, fallback: "no_image.jpg", width: "100%", height: "auto" %>
        </div>

        <div class="col-xs-4">
          <div class="row">
            <h3><%= @product.name %></h3>
            <p><%= @product.explain %></p>
          </div>

          <div class="row">
            <h3>￥<% addtax= @product.price * 1.1 %>
                <%= addtax.round %>円（税込）</h3>
          </div>

          <div class="row">

            <% if @product.sale_status == 1 %>
              <%= form_for(@cart, url:carts_path) do |f| %>
              <%= f.number_field :vol, :value =>1, min: 1 %>
              <%= f.hidden_field :product_id, :value => @product.id %>
              <%= f.submit 'カートに入れる', class: "btn btn-primary" %>
              <% end %>

            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>